### ISSUE TITLE
collections.ChainMap not support in Python2

### ISSUE THREAD

**Issue by monhz** [cool-RR/PySnooper#35]
I am using  Python 2.7.13, when try to use pysnooper.snoop decorator, meet the AttributeError exception, the reason is `collections.ChainMap` is used in tracer.py, which is not supported in Python2.x. 

code is here:
https://github.com/cool-RR/PySnooper/blob/master/pysnooper/tracer.py#L27

hoping PySnooper is fully compatible with python2

**Comment by cool-RR** [comment]
This was a bug that I fixed. Run `pip install pysnooper --upgrade` and if it happens again, reopen this ticket.

**Comment by blargomat** [comment]
unfortunately even after upgrading via pip (tested it just now) i still got:

```
  File "/usr/local/lib/python2.7/dist-packages/pysnooper/tracer.py", line 162, in trace
    get_local_reprs(frame, variables=self.variables)
  File "/usr/local/lib/python2.7/dist-packages/pysnooper/tracer.py", line 28, in get_local_reprs
    locals_and_globals = collections.ChainMap(frame.f_locals, frame.f_globals)
  AttributeError: 'module' object has no attribute 'ChainMap'
```

however this works in tracer.py but requires the chainmap pip package :/

    locals_and_globals = None
    if sys.version_info.major > 2:
        locals_and_globals = collections.ChainMap(frame.f_locals, frame.f_globals)
    else:
        from chainmap import ChainMap
        locals_and_globals = ChainMap(frame.f_locals, frame.f_globals)

**Comment by cool-RR** [comment]
I believe this was just fixed by #38 , please re-upgrade, try again and update here.

**Comment by monhz** [comment]
`from ConfigParser import _Chainmap as ChainMap` works fine in 2.7.

**Comment by blargomat** [comment]
> I believe this was just fixed by #38 , please re-upgrade, try again and update here.

Indeed, i upgraded again and now it works :>
